export const countries = [
  { key: 1, value: "Afghanistan" },
  { key: 2, value: "Albania" },
  { key: 3, value: "Algeria" },
  { key: 4, value: "Andorra" },
  { key: 5, value: "Angola" },
  { key: 6, value: "Antigua & Deps" },
  { key: 7, value: "Argentina" },
  { key: 8, value: "Armenia" },
  { key: 9, value: "Australia" },
  { key: 10, value: "Austria" },
  { key: 11, value: "Azerbaijan" },
  { key: 12, value: "Bahamas" },
  { key: 13, value: "Bahrain" },
  { key: 14, value: "Bangladesh" },
  { key: 15, value: "Barbados" },
  { key: 16, value: "Belarus" },
  { key: 17, value: "Belgium" },
  { key: 18, value: "Belize" },
  { key: 19, value: "Benin" },
  { key: 20, value: "Bhutan" },
  { key: 21, value: "Bolivia" },
  { key: 22, value: "Bosnia Herzegovina" },
  { key: 23, value: "Botswana" },
  { key: 24, value: "Brazil" },
  { key: 25, value: "Brunei" },
  { key: 26, value: "Bulgaria" },
  { key: 27, value: "Burkina" },
  { key: 28, value: "Burundi" },
  { key: 29, value: "Cambodia" },
  { key: 30, value: "Cameroon" },
  { key: 31, value: "Canada" },
  { key: 32, value: "Cape Verde" },
  { key: 33, value: "Central African Rep" },
  { key: 34, value: "Chad" },
  { key: 35, value: "Chile" },
  { key: 36, value: "China" },
  { key: 37, value: "Colombia" },
  { key: 38, value: "Comoros" },
  { key: 39, value: "Congo" },
  { key: 40, value: "Congo {Democratic Rep}" },
  { key: 41, value: "Costa Rica" },
  { key: 42, value: "Croatia" },
  { key: 43, value: "Cuba" },
  { key: 44, value: "Cyprus" },
  { key: 45, value: "Czech Republic" },
  { key: 46, value: "Denmark" },
  { key: 47, value: "Djibouti" },
  { key: 48, value: "Dominica" },
  { key: 49, value: "Dominican Republic" },
  { key: 50, value: "East Timor" },
  { key: 51, value: "Ecuador" },
  { key: 52, value: "Egypt" },
  { key: 53, value: "El Salvador" },
  { key: 54, value: "Equatorial Guinea" },
  { key: 55, value: "Eritrea" },
  { key: 56, value: "Estonia" },
  { key: 57, value: "Ethiopia" },
  { key: 58, value: "Fiji" },
  { key: 59, value: "Finland" },
  { key: 60, value: "France" },
  { key: 61, value: "Gabon" },
  { key: 62, value: "Gambia" },
  { key: 63, value: "Georgia" },
  { key: 64, value: "Germany" },
  { key: 65, value: "Ghana" },
  { key: 66, value: "Greece" },
  { key: 67, value: "Grenada" },
  { key: 68, value: "Guatemala" },
  { key: 69, value: "Guinea" },
  { key: 70, value: "Guinea-Bissau" },
  { key: 71, value: "Guyana" },
  { key: 72, value: "Haiti" },
  { key: 73, value: "Honduras" },
  { key: 74, value: "Hungary" },
  { key: 75, value: "Iceland" },
  { key: 76, value: "India" },
  { key: 77, value: "Indonesia" },
  { key: 78, value: "Iran" },
  { key: 79, value: "Iraq" },
  { key: 80, value: "Ireland {Republic}" },
  { key: 81, value: "Israel" },
  { key: 82, value: "Italy" },
  { key: 83, value: "Ivory Coast" },
  { key: 84, value: "Jamaica" },
  { key: 85, value: "Japan" },
  { key: 86, value: "Jordan" },
  { key: 87, value: "Kazakhstan" },
  { key: 88, value: "Kenya" },
  { key: 89, value: "Kiribati" },
  { key: 90, value: "Korea North" },
  { key: 91, value: "Korea South" },
  { key: 92, value: "Kosovo" },
  { key: 93, value: "Kuwait" },
  { key: 94, value: "Kyrgyzstan" },
  { key: 95, value: "Laos" },
  { key: 96, value: "Latvia" },
  { key: 97, value: "Lebanon" },
  { key: 98, value: "Lesotho" },
  { key: 99, value: "Liberia" },
  { key: 100, value: "Libya" },
  { key: 101, value: "Liechtenstein" },
  { key: 102, value: "Lithuania" },
  { key: 103, value: "Luxembourg" },
  { key: 104, value: "Macedonia" },
  { key: 105, value: "Madagascar" },
  { key: 106, value: "Malawi" },
  { key: 107, value: "Malaysia" },
  { key: 108, value: "Maldives" },
  { key: 109, value: "Mali" },
  { key: 110, value: "Malta" },
  { key: 111, value: "Marshall Islands" },
  { key: 112, value: "Mauritania" },
  { key: 113, value: "Mauritius" },
  { key: 114, value: "Mexico" },
  { key: 115, value: "Micronesia" },
  { key: 116, value: "Moldova" },
  { key: 117, value: "Monaco" },
  { key: 118, value: "Mongolia" },
  { key: 119, value: "Montenegro" },
  { key: 120, value: "Morocco" },
  { key: 121, value: "Mozambique" },
  { key: 122, value: "Myanmar, {Burma}" },
  { key: 123, value: "Namibia" },
  { key: 124, value: "Nauru" },
  { key: 125, value: "Nepal" },
  { key: 126, value: "Netherlands" },
  { key: 127, value: "New Zealand" },
  { key: 128, value: "Nicaragua" },
  { key: 129, value: "Niger" },
  { key: 130, value: "Nigeria" },
  { key: 131, value: "Norway" },
  { key: 132, value: "Oman" },
  { key: 133, value: "Pakistan" },
  { key: 134, value: "Palau" },
  { key: 135, value: "Panama" },
  { key: 136, value: "Papua New Guinea" },
  { key: 137, value: "Paraguay" },
  { key: 138, value: "Peru" },
  { key: 139, value: "Philippines" },
  { key: 140, value: "Poland" },
  { key: 141, value: "Portugal" },
  { key: 142, value: "Qatar" },
  { key: 143, value: "Romania" },
  { key: 144, value: "Russian Federation" },
  { key: 145, value: "Rwanda" },
  { key: 146, value: "St Kitts & Nevis" },
  { key: 147, value: "St Lucia" },
  { key: 148, value: "Saint Vincent & the Grenadines" },
  { key: 149, value: "Samoa" },
  { key: 150, value: "San Marino" },
  { key: 151, value: "Sao Tome & Principe" },
  { key: 152, value: "Saudi Arabia" },
  { key: 153, value: "Senegal" },
  { key: 154, value: "Serbia" },
  { key: 155, value: "Seychelles" },
  { key: 156, value: "Sierra Leone" },
  { key: 157, value: "Singapore" },
  { key: 158, value: "Slovakia" },
  { key: 159, value: "Slovenia" },
  { key: 160, value: "Solomon Islands" },
  { key: 161, value: "Somalia" },
  { key: 162, value: "South Africa" },
  { key: 163, value: "South Sudan" },
  { key: 164, value: "Spain" },
  { key: 165, value: "Sri Lanka" },
  { key: 166, value: "Sudan" },
  { key: 167, value: "Suriname" },
  { key: 168, value: "Swaziland" },
  { key: 169, value: "Sweden" },
  { key: 170, value: "Switzerland" },
  { key: 171, value: "Syria" },
  { key: 172, value: "Taiwan" },
  { key: 173, value: "Tajikistan" },
  { key: 174, value: "Tanzania" },
  { key: 175, value: "Thailand" },
  { key: 176, value: "Togo" },
  { key: 177, value: "Tonga" },
  { key: 178, value: "Trinidad & Tobago" },
  { key: 179, value: "Tunisia" },
  { key: 180, value: "Turkey" },
  { key: 181, value: "Turkmenistan" },
  { key: 182, value: "Tuvalu" },
  { key: 183, value: "Uganda" },
  { key: 184, value: "Ukraine" },
  { key: 185, value: "United Arab Emirates" },
  { key: 186, value: "United Kingdom" },
  { key: 187, value: "United States" },
  { key: 188, value: "Uruguay" },
  { key: 189, value: "Uzbekistan" },
  { key: 190, value: "Vanuatu" },
  { key: 191, value: "Vatican City" },
  { key: 192, value: "Venezuela" },
  { key: 193, value: "Vietnam" },
  { key: 194, value: "Yemen" },
  { key: 195, value: "Zambia" },
  { key: 196, value: "Zimbabwe" },
];
